---
title: "Assumptions"
author: "Rachel Bash"
date: "12/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes



### NMBGMR

Pulled data by creating a loop that pulled each site number from website from csv

Do not know coordinate references system they used. Converted Easting/Northing coordinates to Lat/Long coordinates with 4326 projection.

Some sites were lost 6090 -> 5337 because there were no Easting/Northing coordinates.

### USGS

Pulled from NWIS dataRetrieval package, last pull was on 12/7/2019.

Data coordinate system was NAD83 or crs 4269.

Did a left join pulling gwl and sites. Assumed that all sites had gwl data.Removed a lot of potential groundwater wells without any data attached to them. 9778 sites with no gwl data

### NGWMN 

Downloaded zipfile from website, saved under Raw folder
Projection is in 4269


### OSE

Downloaded shapefile from OSE website. Data dictionary: http://www.ose.state.nm.us/GIS/PODS/nmose_WATERS_PODs_data_dictionary_v8.xlsx

For depth to water, used static_level column, and for Date and Time, I used sys_date

Translated geometry in 4269.

OSEWellID are not unique (there are 85 sites with an OSEWellID of 1) - for future reference, will need to convert to unique identifyer (or use OBJECTID) for gwl data in order for it to show up on the map. Will not include in map for now.


### ABQ

No location information like lat or long data. No actual gwl data. Should not be included in final map


