---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(leaflet)
library(highcharter)
library(ggplot2)

latitude<-c(35.94077, 35.83770, 35.84545, 35.81584, 35.79387, 36.05600, 35.94077)
longitude<-c(-78.58010, -78.78084, -78.72444, -78.62568, -78.64262,-78.67600, -78.58010)
amounts1<-c(27, 44, 34, 46, 25, 15, 28)
amounts2<-c(34, 52, 35, 78, 14, 24, 20)
ids<-c("a", "b", "c", "d", "e", "f", "a")
df<-data.frame(ids,amounts1,amounts2,latitude,longitude)
values1<-c(44, 58, 25, 13, 35,  7, 27, 14, 81, 29, 40, 83)
values2<-c(3, 18, 55, 37, 43, 87, 50, 19, 22, 26, 54, 64)
ids2<-c("a", "b", "c", "d", "e", "f", "a", "b", "c", "d", "e", "f")
df2<-data.frame(ids2, values1, values2)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
output$map <- renderLeaflet({

  leaflet() %>%
    addTiles() %>%
    addMarkers(data = df, lng = longitude, lat = latitude, 
               layerId = ~ids)

})

leafletOutput('map')  

```

Column {data-width=350}
-----------------------------------------------------------------------

```{r}

click_marker <- eventReactive(input$map_marker_click, {

  x <- input$map_marker_click

  return(x$id)

})

data_for_chart <- reactive({

  return(df2[df2$ids2 == click_marker(), ])

})

output$chart <- renderPlot({

  ggplot(data_for_chart(), aes(x=values1, y=values2)) + 
    geom_point()

})

plotOutput('chart')

```